# https://taskfile.dev

version: '3'

vars:
  DOCKER_IMAGE_NAME: local.io/mleuthold/jupyter/pyspark-notebook
  DOCKER_IMAGE_TAG: spark-3.2.0

tasks:
  build-docker-image:
    desc: Builds Docker image.
    cmds:
    - |
      docker build \
      -t {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}} \
      .

  run-docker-container:
    desc: Runs Docker container.
    cmds:
    - |
      docker run -it --rm \
      -p 8888:8888 \
      -p 4040:4040 \
      --user root \
      -e GRANT_SUDO=yes \
      -e AWS_PROFILE=$AWS_PROFILE \
      -v "$HOME/.aws":/home/jovyan/.aws \
      -v "$HOME":/home/jovyan/work \
      {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}}

  poetry-mgmt:
    desc: start a Python environment with Poetry pre installed
    cmds:
    - >
      docker run -it --rm
      -v $(pwd):/project
      -w /project
      {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}} bash